version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tidetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/tidetracker?sslmode=disable
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./TideTracker

volumes:
  postgres_data:
